agents:
  queue: "mac"

steps:
  - label: ":building_construction: Test 6 - Build Failure Detection"
    key: "test-1"
    command: |
      echo "This step succeeds, but checking if build is failing..."
    plugins:
      - https://github.com/buildkite-plugins/incident-pagerduty-buildkite-plugin.git#73e5852:
          integration-key: ${INTEGRATION_KEY}
          check: build
          debug: true

  - label: ":white_check_mark: Test 8 - Success (No Incident Expected)"
    key: "test-2"
    command: |
      echo "This step succeeds - no incident should be created"
      echo "Verifying plugin doesn't create false positives"
    plugins:
      - https://github.com/buildkite-plugins/incident-pagerduty-buildkite-plugin.git#73e5852:
          integration-key: ${INTEGRATION_KEY}
        
secrets:
  INTEGRATION_KEY: pagerduty_integration_key
  BUILDKITE_API_TOKEN: api_token
