agents:
  queue: "mac"

steps:
  - label: ":x: Simulated failing job"
    key: "fail-setup"
    command: |
      echo "Simulating a failing job to exercise build-level detection"
      exit 1

  - label: ":building_construction: Build Failure Detection"
    key: "test-1"
    depends_on: "fail-setup"
    allow_dependency_failure: true
    command: |
      echo "This step succeeds, but checking if build is failing..."
    plugins:
      - https://github.com/buildkite-plugins/incident-pagerduty-buildkite-plugin.git#73e5852:
          integration-key: ${INTEGRATION_KEY}
          check: build
          debug: true

  - label: ":white_check_mark: Success (No Incident Expected)"
    key: "test-2"
    command: |
      echo "This step intentionally fails to trigger job-level detection"
      exit 1
    plugins:
      - https://github.com/buildkite-plugins/incident-pagerduty-buildkite-plugin.git#73e5852:
          integration-key: ${INTEGRATION_KEY}
          check: job
        
secrets:
  INTEGRATION_KEY: pagerduty_integration_key
  BUILDKITE_API_TOKEN: api_token
